### ISSUE TITLE
Error when build app

### ISSUE THREAD

**Issue by deamul1sk** [saltedge/sca-authenticator-ios#65]
Hi team, 

**Summary:**  
`I have an error when building app`

**Steps to reproduce:**  
1.  I build app 
<img width="1440" alt="Screen Shot 2020-01-13 at 14 14 39" src="https://user-images.githubusercontent.com/36152586/72238090-5a8fbc00-360f-11ea-933a-abd991dbc517.png">
<img width="382" alt="Screen Shot 2020-01-13 at 14 17 44" src="https://user-images.githubusercontent.com/36152586/72238144-7eeb9880-360f-11ea-8109-b586b437a6e6.png">
 The app is stopped at this screen

2.  Then i get an error related to SaltedgeAuthenticatorSDK
<img width="1440" alt="Screen Shot 2020-01-13 at 14 20 38" src="https://user-images.githubusercontent.com/36152586/72238344-0b965680-3610-11ea-9f3d-18dec702d597.png">

Looking forward to your early reply.

Thanks, 
Deam

**Comment by baller784** [comment]
Hello @deamul1sk!

Thank you for your contribution to our project. We have reviewed your issue and already resolved the problem. The problem was with Firebase configuration. So, if you would like to have Crashlytics in your project, please generate `GoogleService-Info.plist`. For now reference to `GoogleService-Info.plist` was removed from the project. Please make sure to pull latest changes.

**Comment by deamul1sk** [comment]
Hi @ConstantinKV, @baller784 

Thank you for your support, I have fixed this issue. Currently, I'm learning about SCA, I have built an Identity Server (https://github.com/saltedge/sca-identity-service-example) and is building a Authenticator app. Thank you very much. If you don't mind, I'll bother you ✌️  ✌️  

<img width="358" alt="Screen Shot 2020-01-14 at 10 19 49" src="https://user-images.githubusercontent.com/36152586/72311489-70f15280-36b7-11ea-9d5f-eb0ead37e4bf.png">

Thanks,
Deam
